//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<explik_competition> explik_competition { get; set; }
        public virtual DbSet<explik_competitionpage> explik_competitionpage { get; set; }
        public virtual DbSet<explik_course> explik_course { get; set; }
        public virtual DbSet<explik_coursepage> explik_coursepage { get; set; }
        public virtual DbSet<explik_pagecontent> explik_pagecontent { get; set; }
        public virtual DbSet<explik_pages> explik_pages { get; set; }
        public virtual DbSet<explik_siteconfiguration> explik_siteconfiguration { get; set; }
        public virtual DbSet<explik_users> explik_users { get; set; }
        public virtual DbSet<explik_alerts> explik_alerts { get; set; }
        public virtual DbSet<explik_comments> explik_comments { get; set; }
    }
}
