//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class explik_pages
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Tags { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsLocked { get; set; }
        public string ControlledBy { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public bool IsVideo { get; set; }
        public bool IsSubmitted { get; set; }
        public bool IsControlled { get; set; }
        public bool IsRejected { get; set; }
        public bool IsCopied { get; set; }
        public Nullable<int> NbRating { get; set; }
        public Nullable<int> TotalRating { get; set; }
        public Nullable<int> NbView { get; set; }
        public string FilePath { get; set; }
        public string VideoUrl { get; set; }
        public string Pseudonym { get; set; }
        public Nullable<int> ControllerRating { get; set; }
        public Nullable<int> CompetitionId { get; set; }
    }
}
