//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class explik_pagecontent
    {
        public string Id { get; set; }
        public string ControlledBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public int VersionNumber { get; set; }
        public string Text { get; set; }
        public int PageId { get; set; }
    }
}
