//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class explik_users
    {
        public string Id { get; set; }
        public string ActivationKey { get; set; }
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public bool IsEditor { get; set; }
        public bool IsController { get; set; }
        public string AttachmentsPath { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<int> Contribution { get; set; }
        public Nullable<int> DisplayFlags { get; set; }
        public string Password { get; set; }
        public string PasswordResetKey { get; set; }
        public string Salt { get; set; }
        public string Username { get; set; }
    }
}
