//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class explik_competitionpage
    {
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int PageId { get; set; }
        public Nullable<int> NbRating { get; set; }
        public Nullable<int> TotalRating { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Ranking { get; set; }
    }
}
