//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Database.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class explik_competition
    {
        public int Id { get; set; }
        public System.DateTime PublicationStart { get; set; }
        public System.DateTime PublicationStop { get; set; }
        public System.DateTime RatingStart { get; set; }
        public System.DateTime RatingStop { get; set; }
        public string PageTag { get; set; }
        public int PageId { get; set; }
        public int Status { get; set; }
    }
}
