SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS explik_pages;
DROP TABLE IF EXISTS explik_pagecontent;
DROP TABLE IF EXISTS explik_users;
DROP TABLE IF EXISTS explik_siteconfiguration;
DROP TABLE IF EXISTS explik_comments;
DROP TABLE IF EXISTS explik_alerts;
DROP TABLE IF EXISTS explik_competition;
DROP TABLE IF EXISTS explik_competitionpages;
SET FOREIGN_KEY_CHECKS = 1;